import {
  buttonColorValues,
  buttonVariantValues,
  iconPlaygroundValues,
  radiusValues,
  sizeValues,
} from "@/dev/values";
import { fontFaceLabels, fontFaceValues } from "@/fonts";
import type { ComponentMeta } from "./types";

export const buttonMeta = {
  name: "Button",
  slug: "button",
  kind: "ui",
  file: "src/components/ui/button/button.tsx",
  importStatement: 'import { Button, buttonVariants } from "@/components/ui/button";',
  description:
    "Native button with variants, colors, sizes, token radius, catalog font, and a logical start/end icon.",
  rules: [
    "Pass the label as children. Do not hardcode copy inside Button.",
    "Default font is Heebo Regular; Ubuntu Medium is the alternate label face.",
    "Use icon and iconPosition start|end — never left/right icon props.",
    "Icon-only (icon and no label) uses equal padding and the same height as size.",
    "Reuse buttonVariants() on Link or other tags when you need the same chrome without a button element.",
    "Color tints filled, outline, soft, tinted, ghost, subtle, link, and muted. Tokens only — no hex.",
    "tinted matches soft but the inset border uses the color token (shadow-outline-sm-*), not border-border.",
  ],
  props: [
    {
      name: "children",
      type: "string",
      default: "Button",
      description: "Button label. Omit with icon for an icon-only control.",
      playground: true,
      group: "Demo",
    },
    {
      name: "variant",
      type: "enum",
      values: [...buttonVariantValues],
      default: "filled",
      description: "Visual style.",
      playground: true,
      group: "Appearance",
    },
    {
      name: "color",
      type: "enum",
      values: [...buttonColorValues],
      default: "primary",
      description: "Action color token.",
      playground: true,
      group: "Appearance",
    },
    {
      name: "size",
      type: "enum",
      values: [...sizeValues],
      default: "md",
      description: "Fixed height / padding / type: sm 32/12/14, md 34/14/16, lg 40/16/18 (px).",
      playground: true,
      group: "Appearance",
    },
    {
      name: "font",
      type: "enum",
      values: [...fontFaceValues],
      default: "heeboRegular",
      description: `Catalog face. Default Heebo Regular; alternate Ubuntu Medium. ${fontFaceValues.map((key) => `${key}=${fontFaceLabels[key]}`).join("; ")}.`,
      playground: true,
      group: "Appearance",
    },
    {
      name: "radius",
      type: "enum",
      values: [...radiusValues],
      default: "full",
      description: "Corner radius token (theme.radius).",
      playground: true,
      group: "Appearance",
    },
    {
      name: "icon",
      type: "enum",
      values: [...iconPlaygroundValues],
      default: "",
      description: "IconName from @/components/icons.",
      playground: true,
      group: "Icon",
    },
    {
      name: "iconPosition",
      type: "enum",
      values: ["start", "end"],
      default: "start",
      description: "Logical side for the icon when a label is present.",
      playground: true,
      group: "Icon",
    },
    {
      name: "disabled",
      type: "boolean",
      default: false,
      description: "Native disabled state.",
      playground: true,
      group: "State",
    },
    {
      name: "className",
      type: "string",
      description: "Merged onto the root with cn().",
      playground: false,
    },
  ],
} satisfies ComponentMeta;
