import {
  cardBackgroundColorValues,
  cardBorderColorValues,
  cardLightValues,
  cardSlotVariantValues,
  cardSurfaceValues,
  cardUnderlineSizeValues,
  cardUnderlineWidthValues,
  borderValues,
  paddingValues,
  radiusValues,
} from "@/dev/values";
import type { ComponentMeta } from "./types";

export const cardMeta = {
  name: "Card",
  slug: "card",
  kind: "ui",
  file: "src/components/ui/card/card.tsx",
  importStatement:
    'import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card";',
  description:
    "Compound surface: Card + Header / Content / Footer. No copy and no Button import. Lights and start/end edges follow dir.",
  rules: [
    "Compose the slots. Do not invent a second card chrome on templates.",
    "surface is only the fill (panel or glass). Lights are independent ellipse glows.",
    "borderLight* paints a fade on that box-border edge and follows radius. Needs border ≠ none.",
    "lightStart / lightEnd and borderLightStart / borderLightEnd follow dir — not left/right.",
    "borderColor: border (neutral), {color} (20% mix), or {color}Active (full). backgroundColor: none (default) | border | {color} — 10% opacity overlay on the existing surface (spots + base unchanged). Header/Footer variant border|divider inherit the parent Card border width and borderColor. border insets the line by slot padding; divider stays full width.",
    "CardHeader underline is a token-height bar at the header bottom (underlineSize sm/md/lg = border width 1/2/3px; underlineWidth fix 50px or 25/50/75%). Start inset matches padding. It stacks with variant border/divider (underline is ::before; the edge is ::after).",
    "CardContent fills leftover space (flex-1 min-h-0). Header and Footer stay shrink-0.",
  ],
  props: [
    {
      name: "title",
      type: "string",
      default: "Title",
      description: "Demo header children (not a Card root prop).",
      playground: true,
      group: "Demo",
    },
    {
      name: "content",
      type: "string",
      default: "Content",
      description: "Demo text in CardContent.",
      playground: true,
      group: "Demo",
    },
    {
      name: "surface",
      type: "enum",
      values: [...cardSurfaceValues],
      default: "panel",
      description: "Fill: panel uses --panel; glass is the stuck-header mix plus blur.",
      playground: true,
      group: "Surface",
    },
    {
      name: "lightBottom",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Bottom ellipse glow.",
      playground: true,
      group: "Lights",
    },
    {
      name: "lightTop",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Top ellipse glow.",
      playground: true,
      group: "Lights",
    },
    {
      name: "lightStart",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Logical start ellipse glow (follows dir).",
      playground: true,
      group: "Lights",
    },
    {
      name: "lightEnd",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Logical end ellipse glow (follows dir).",
      playground: true,
      group: "Lights",
    },
    {
      name: "borderLightTop",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Top edge gradient on the box border (needs border ≠ none).",
      playground: true,
      group: "Border light top",
    },
    {
      name: "borderLightTopStart",
      type: "number",
      default: 10,
      description: "Top border-light start stop percent.",
      playground: true,
      group: "Border light top",
      dependsOn: "borderLightTop",
    },
    {
      name: "borderLightTopCenter",
      type: "number",
      default: 50,
      description: "Top border-light center stop percent.",
      playground: true,
      group: "Border light top",
      dependsOn: "borderLightTop",
    },
    {
      name: "borderLightTopEnd",
      type: "number",
      default: 90,
      description: "Top border-light end stop percent.",
      playground: true,
      group: "Border light top",
      dependsOn: "borderLightTop",
    },
    {
      name: "borderLightBottom",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Bottom edge gradient on the box border (needs border ≠ none).",
      playground: true,
      group: "Border light bottom",
    },
    {
      name: "borderLightBottomStart",
      type: "number",
      default: 10,
      description: "Bottom border-light start stop percent.",
      playground: true,
      group: "Border light bottom",
      dependsOn: "borderLightBottom",
    },
    {
      name: "borderLightBottomCenter",
      type: "number",
      default: 50,
      description: "Bottom border-light center stop percent.",
      playground: true,
      group: "Border light bottom",
      dependsOn: "borderLightBottom",
    },
    {
      name: "borderLightBottomEnd",
      type: "number",
      default: 90,
      description: "Bottom border-light end stop percent.",
      playground: true,
      group: "Border light bottom",
      dependsOn: "borderLightBottom",
    },
    {
      name: "borderLightStart",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Logical start edge gradient on the box border (follows dir).",
      playground: true,
      group: "Border light start",
    },
    {
      name: "borderLightStartStart",
      type: "number",
      default: 10,
      description: "Start border-light start stop percent.",
      playground: true,
      group: "Border light start",
      dependsOn: "borderLightStart",
    },
    {
      name: "borderLightStartCenter",
      type: "number",
      default: 50,
      description: "Start border-light center stop percent.",
      playground: true,
      group: "Border light start",
      dependsOn: "borderLightStart",
    },
    {
      name: "borderLightStartEnd",
      type: "number",
      default: 90,
      description: "Start border-light end stop percent.",
      playground: true,
      group: "Border light start",
      dependsOn: "borderLightStart",
    },
    {
      name: "borderLightEnd",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description: "Logical end edge gradient on the box border (follows dir).",
      playground: true,
      group: "Border light end",
    },
    {
      name: "borderLightEndStart",
      type: "number",
      default: 10,
      description: "End border-light start stop percent.",
      playground: true,
      group: "Border light end",
      dependsOn: "borderLightEnd",
    },
    {
      name: "borderLightEndCenter",
      type: "number",
      default: 50,
      description: "End border-light center stop percent.",
      playground: true,
      group: "Border light end",
      dependsOn: "borderLightEnd",
    },
    {
      name: "borderLightEndEnd",
      type: "number",
      default: 90,
      description: "End border-light end stop percent.",
      playground: true,
      group: "Border light end",
      dependsOn: "borderLightEnd",
    },
    {
      name: "padding",
      type: "enum",
      values: [...paddingValues],
      default: "none",
      description: "Root padding. Slots have their own padding (default md).",
      playground: true,
      group: "Layout",
    },
    {
      name: "radius",
      type: "enum",
      values: [...radiusValues],
      default: "lg",
      description: "Corner radius token.",
      playground: true,
      group: "Layout",
    },
    {
      name: "border",
      type: "enum",
      values: [...borderValues],
      default: "sm",
      description: "Border width token.",
      playground: true,
      group: "Layout",
    },
    {
      name: "borderColor",
      type: "enum",
      values: [...cardBorderColorValues],
      default: "border",
      description:
        "Border color token. border = neutral. primary etc. = 20% mix. primaryActive etc. = full color.",
      playground: true,
      group: "Layout",
    },
    {
      name: "backgroundColor",
      type: "enum",
      values: [...cardBackgroundColorValues],
      default: "none",
      description:
        "Surface tint overlay. none = off. border or action colors = 10% opacity wash on top of panel/glass and lights.",
      playground: true,
      group: "Layout",
    },
    {
      name: "headerVariant",
      type: "enum",
      values: [...cardSlotVariantValues],
      default: "none",
      description: "CardHeader variant.",
      playground: true,
      group: "Slots",
    },
    {
      name: "footerVariant",
      type: "enum",
      values: [...cardSlotVariantValues],
      default: "none",
      description: "CardFooter variant.",
      playground: true,
      group: "Slots",
    },
    {
      name: "headerUnderline",
      type: "enum",
      values: [...cardLightValues],
      default: "none",
      description:
        "CardHeader accent bar color. Size and width are separate props.",
      playground: true,
      group: "Slots",
    },
    {
      name: "headerUnderlineSize",
      type: "enum",
      values: [...cardUnderlineSizeValues],
      default: "md",
      description: "Underline height from theme.borderWidth (sm 1px, md 2px, lg 3px).",
      playground: true,
      group: "Slots",
      dependsOn: "headerUnderline",
    },
    {
      name: "headerUnderlineWidth",
      type: "enum",
      values: [...cardUnderlineWidthValues],
      default: "fix",
      description: "Underline width: fix 50px, or 25/50/75 percent.",
      playground: true,
      group: "Slots",
      dependsOn: "headerUnderline",
    },
    {
      name: "headerPadding",
      type: "enum",
      values: [...paddingValues],
      default: "md",
      description: "CardHeader padding. border inset matches this; divider stays full width.",
      playground: true,
      group: "Slots",
    },
    {
      name: "contentPadding",
      type: "enum",
      values: [...paddingValues],
      default: "md",
      description: "CardContent padding.",
      playground: true,
      group: "Slots",
    },
    {
      name: "footerPadding",
      type: "enum",
      values: [...paddingValues],
      default: "md",
      description: "CardFooter padding. border inset matches this; divider stays full width.",
      playground: true,
      group: "Slots",
    },
    {
      name: "className",
      type: "string",
      description: "Merged onto the root with cn().",
      playground: false,
    },
  ],
} satisfies ComponentMeta;
