export {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  cardContentVariants,
  cardFooterVariants,
  cardHeaderVariants,
  cardVariants,
  resolveCardBackgroundColor,
  resolveCardBorderColor,
  type CardBackgroundColor,
  type CardBorderColor,
  type CardContentProps,
  type CardFooterProps,
  type CardHeaderProps,
  type CardProps,
} from "./card";
