export const copy = {
  siteName: "Component lab",
  siteLink: "Site",
  dirLtr: "LTR",
  dirRtl: "RTL",
  dirToggle: "Preview direction",
  hatch: "Hatch",
  hatchToggle: "Toggle hatch background",
  reset: "Reset",
  resetToggle: "Reset playground to defaults",
  guide: "Guide",
  gettingStarted: "Getting started",
  tokens: "Tokens",
  components: "Components",
  templates: "Templates",
  icons: "Icons",
  props: "Props",
  prop: "Prop",
  type: "Type",
  default: "Default",
  description: "Description",
  agentRules: "Agent rules",
  playground: "Playground",
  gallery: "Gallery",
  test: "Test",
  none: "None",
  home: {
    title: "Component lab",
    intro:
      "English-only docs and playgrounds for Prowem UI, templates, and icons. Use the playground LTR/RTL control to test logical CSS. There is no dark mode and no locale routing here.",
    foldersTitle: "Removable folders",
    foldersIntro:
      "The lab is isolated from the product. Delete both folders (or leave them in .dockerignore) and production is unchanged. Product code must not import them.",
    folders: [
      "src/app/dev — routes under /dev (layout, pages).",
      "src/dev — English copy, meta, chrome, playgrounds, and permutation galleries.",
    ],
    dockerTitle: "Docker",
    dockerIntro:
      ".dockerignore excludes src/app/dev and src/dev so the production image has no /dev routes. Remove those two lines if you want this lab in a build for new engineers or AI agents.",
    addTitle: "Add a UI component",
    add: [
      "Create src/components/ui/<name>/ with cva variants, an exported props type, className + cn(), and index.ts.",
      "Add src/dev/meta/<name>.ts and register it in src/dev/meta/index.ts.",
      "Add a playground renderer in src/dev/playground/renderers.tsx.",
      "Add a permutation gallery in src/dev/gallery when the component has variants to show.",
      "The /dev/components/[slug] page is generated from meta. Do not hardcode a new page.",
    ],
    catalogTitle: "Catalog",
  },
  tokensPage: {
    title: "Tokens",
    intro: "Values come from getSettings() (src/settings/default.json today). Classes are the token names in globals.css.",
    hint: "src/settings/default.json",
    layoutTab: "Layout",
    colorTab: "Color",
    radiusTab: "Radius",
    borderTab: "Border",
    typeTab: "Type",
    layoutIntro:
      "Prefix widths live in globals.css. Container max-widths live in theme.container. Keep the pixel values the same. full is Container only.",
    typeIntro:
      "Local faces in src/fonts. Type scale tokens (text-h1…text-h6, text-body, text-label) live in globals.css. font prop picks catalog faces; size is not a prop.",
  },
  iconsPage: {
    title: "Icons",
    intro: "Names come from src/components/icons/registry.ts. Linear glyphs use currentColor; flags keep national fills.",
    hint: "src/components/icons",
  },
  testPage: {
    title: "Test sandbox",
    intro:
      "Scratch space for new UI ideas. Edit src/dev/test/test-sandbox.tsx only — product code must not import it.",
    steps: [
      "Build the idea in TestSection blocks below (hatch + LTR/RTL help spot layout issues).",
      "Scratch tokens live in src/app/globals.css as --test-* (e.g. --test → bg-test).",
      "When it looks right, tell the agent which section to port and where (e.g. Card border variant).",
      "The agent moves the final version into src/components/ui or templates and updates meta/gallery/docs.",
    ],
    placeholder: "Add Cards, Buttons, custom borders, or any markup in this section.",
  },
  demo: {
    menuItemOne: "Item one",
    menuItemTwo: "Item two",
    cancel: "Cancel",
    confirm: "Confirm",
    cardTitle: "Title",
    cardContent: "Content",
    getStarted: "Get Started",
    heading: "Heading",
    text: "Short supporting copy for the lab.",
    codeSample: 'import { Button } from "@/components/ui/button";',
    label: "Label",
    placeholder: "Type here",
    value: "Preview",
    badge: "Badge",
    alert: "Use this for a short status message.",
    tooltip: "More detail",
    popupTitle: "Title",
    popupBody: "Popup body copy.",
    tabOne: "One",
    tabTwo: "Two",
    tabOneBody: "First panel.",
    tabTwoBody: "Second panel.",
    optionOne: "One",
    optionTwo: "Two",
    optionThree: "Three",
    optionThirty: "Thirty",
    choose: "Choose",
    search: "Search",
    empty: "No matches",
    nav: {
      language: "Language",
      menu: "Menu",
      close: "Close",
      home: "Home",
      myEventApp: "My Event-App",
      myBroadcast: "My Broadcast",
      mySocialmedia: "My Socialmedia",
      myClub: "My Club",
      eventTeam: "Prowem Event Team",
      login: "Login",
      getStarted: "Get Started",
    },
  },
} as const;
